<a href="https://colab.research.google.com/github/JeffShearer/Python/blob/master/fcc-analysis/fcc_data_analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy

In [2]:
import numpy as np
import sys

numpy arrays are similar to python lists. 

In [13]:
a = np.array([1,2,3,4])
b = np.array([
    #c0   #c1  #c2
    ['a', 'b', 'c'], # r 0
    ['d', 'e', 'f'], # r 1
    ['g', 'h', 'i'] # r 2
])


In [11]:
a[3], b[0]

(4, 0.0)

But with arrays you can quickly create matricies (multidimensional arrays) and easily access specific elements with the : notation

In [17]:
b.shape

(3, 3)

The code below isolates row 0, and column 1

In [24]:
print(b[:1,1:2])


[['b']]


Or assign a new value to an entire row or column

In [26]:
b[2] = 99
print(b)

[['a' 'b' 'c']
 ['d' 'e' 'f']
 ['9' '9' '9']]


You can also run vectorized, operations, like add 10 to each element of an array, or add the operation to a new array, similar to list comprehensions like [i + 10 for i in list] - Note that a+10 creates a NEW array. it doesn't modify a, unless you specify a = new operation



In [38]:
a = np.array([0,1,2,3])
a+10

Boolean array comparison - Which values are greater than 2?

In [39]:
a >= 2

array([ True,  True,  True,  True])

Now give me all the avlues greater than 2

In [35]:
a[a>=2]

array([2, 3])

In [34]:
a.mean()

1.5

# Pandas

Note - if you use pandas, you need to import numpy too, as the former uses it. 

In [40]:
import pandas as pd
import numpy as np

## Series

Series and data frames are pandas two main data structures. 
Data frames are spreadsheet like structures - rows and columns. 
Series - sequence of elements ordered by an index, a bit like a python list (if you don't specify an index, it'll just do it numerically starting at 0

You can also set an index of values you choose. Making it kinda like a python dictionary, although it's ordered, unlike a dictionary

In [64]:
g = pd.Series([200,100,5000,30000], index =['usa','canada','uk','germany'])
g.name = 'Series Test'
g

usa          200
canada       100
uk          5000
germany    30000
Name: Series Test, dtype: int64

In [58]:
g.values

array([  200,   100,  5000, 30000])

Look up series items with their index name (or their position [0], etc). Can also do multiples - note double brackets!

In [71]:
g['usa']

200

In [70]:
g[['usa','germany']]

usa          200
germany    30000
Name: Series Test, dtype: int64

Note - in python, the upper limit isn't  included when searching a list like [0:2], only items 0 and 1 are returned, but in pandas, the upper limit IS included.

Like with numpy, you can perform operations on series, like find the values greater than a number

In [87]:
g[g > g.mean()]


germany    30000
Name: Series Test, dtype: int64

In [86]:
g[(g > 1000) & (g < 10000)]

uk    5000
Name: Series Test, dtype: int64

or just return the boolean results

In [89]:
g > 1000

usa        False
canada     False
uk          True
germany     True
Name: Series Test, dtype: bool

Modify series based on criteria


In [92]:
g[g < 500] = g*1.5
g

usa          450
canada       225
uk          5000
germany    30000
Name: Series Test, dtype: int64

## Data Frames

Youll use these a ton with imported data from files, apis.

In [96]:
d = pd.DataFrame({
    'industry': ['metal','agri','electronics'],
    'Revenue': [500,1000,250]
})
d.index = ['abc','xyz','pty']
d


industry  Revenue
abc        metal      500
xyz         agri     1000
pty  electronics      250

In [100]:
d.describe()

Revenue
count     3.000000
mean    583.333333
std     381.881308
min     250.000000
25%     375.000000
50%     500.000000
75%     750.000000
max    1000.000000

In [101]:
d.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3 entries, abc to pty
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   industry  3 non-null      object
 1   Revenue   3 non-null      int64 
dtypes: int64(1), object(1)
memory usage: 180.0+ bytes


When you search for an element of the dataframe, it returns a value almost like a series, where the series name = the index. So in some ways, a data frame is a list of series. Below - select last row in a data frame using iloc

In [105]:
d.iloc[-1]

industry    electronics
Revenue             250
Name: pty, dtype: object

Use .loc with the row index

In [109]:
d.loc['abc']

industry    metal
Revenue       500
Name: abc, dtype: object

or get the whole column

In [106]:
d['Revenue']

abc     500
xyz    1000
pty     250
Name: Revenue, dtype: int64